openapi: 3.0.0
tags:
  - name: Tasks
    description: API operations related to tasks
x-stoplight:
  id: hv9aajgmhu4sd
info:
  title: Template
  version: "1.0"
  description: endpoint list for task
  license:
    name: Your License Name
    url: "https://example.com/license"
  contact:
    name: Your Name
    email: your.email@example.com
    url: example.com
servers:
  - url: "http://localhost:3000"
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        "200":
          description: Shared Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/baseResponse"
                  - x-stoplight:
                      id: nb66j29zb1t22
                    type: object
                    properties:
                      data:
                        type: array
                        x-stoplight:
                          id: rsxhwlxaorsa7
                        items:
                          $ref: "#/components/schemas/Task"
              examples:
                Example 1:
                  value:
                    message: success
                    timestamp: 1707190114
                    process_time: 130
                    data:
                      - id: 1
                        title: write timesheet
                        status: 1
                      - id: 2
                        title: daily standup
                        status: 0
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/baseResponse"
              examples:
                Example 1:
                  value:
                    response_header:
                      success: false
                      message: error getting tasks
                      process_time: 0
      operationId: get-tasks
      x-stoplight:
        id: oqfrdy44c609p
      description: "Get "
    post:
      summary: Create task
      operationId: post-tasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/baseResponse"
              examples:
                Example 1:
                  value:
                    message: success
                    timestamp: 1707190114
                    process_time: 150
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/baseResponse"
              examples:
                Example 1:
                  value:
                    message: error
                    timestamp: 1707190114
                    process_time: 210
      x-stoplight:
        id: mloywbl6oucmp
      description: Add Task
      parameters: []
      requestBody:
        description: Request to add task
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: icbplm9w7d1qb
            examples:
              Example 1:
                value:
                  title: task 1
  "/tasks/{taskId}":
    parameters:
      - schema:
          type: integer
          format: int64
        name: taskId
        in: path
        description: existing task id to be find
        required: true
    get:
      summary: Get specific task by id
      responses:
        "200":
          description: Shared Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/baseResponse"
                  - type: object
                    x-stoplight:
                      id: d0w1se1ialpql
                    properties:
                      data:
                        $ref: "#/components/schemas/Task"
        "500":
          description: Shared Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/baseResponse"
              examples:
                Example 1:
                  value:
                    message: string
                    timestamp: 0
                    process_time: 0
      operationId: get-tasks-taskId
      x-stoplight:
        id: a1h8yepfkwlh2
      parameters: []
      description: Get specific task by task_id
    put:
      summary: Update task
      responses:
        "200":
          $ref: "#/components/responses/BaseResponse"
        "500":
          $ref: "#/components/responses/BaseResponse"
      operationId: put-tasks-taskId
      x-stoplight:
        id: k9z4qowh5iuyu
      requestBody:
        description: task properties to update
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: r8109c3qr0l2f
            examples:
              Example 1:
                value:
                  title: title baru
      description: Update task detail
    delete:
      summary: Delete task
      responses:
        "200":
          $ref: "#/components/responses/BaseResponse"
        "500":
          $ref: "#/components/responses/BaseResponse"
      operationId: delete-tasks-taskId
      x-stoplight:
        id: 2yfk80l989she
      description: delete task endpoint
components:
  schemas:
    Task:
      title: Task
      x-stoplight:
        id: 6ik83chrljzbx
      type: object
      description: Model for task
      properties:
        id:
          type: integer
          x-stoplight:
            id: 4jpc8wh7caqgc
          format: int64
        title:
          type: string
          x-stoplight:
            id: lrx0s4fejkav7
        status:
          type: integer
          x-stoplight:
            id: 1ewevm6jvwqhd
    baseResponse:
      title: Base Response
      x-stoplight:
        id: 03wbo9cgnjofn
      type: object
      x-examples:
        Example 1:
          error_code: string
          error_message: string
      properties:
        error_code:
          type: string
          x-stoplight:
            id: ip18nrnkuqm0r
        error_message:
          type: string
          x-stoplight:
            id: x1z7jh9sdutiu
  responses:
    BaseResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/baseResponse"
          examples:
            Example 1:
              value:
                message: fail
                timestamp: 1231230
                process_time: 510
                error_code: ""
                custom_value: ""
            Example 2:
              value:
                message: success
                timestamp: 123123123
                process_time: 10
x-internal: false
